### ISSUE TITLE
remove tegola.Geometry type from Map.Encode

### ISSUE THREAD

**Issue by ear7h** [go-spatial/tegola#628]
The following functions have to be converted:
- [x] `basic.ToWebMercator` issue: #622, pr: #625 
- [x] `simplify.SimplifyGeometry`  pr: #648
- [x] `mvt.ScaleGeo` pr: #629
- [x] `validate.CleanGeometry` \* commit: 4136aed8f86c8fbc268c7e757ffb0ba37ccd1376

~Afterwards, the `mvt` package as a whole should be cleaned.~ #629 

\* clean geometry, as it stands, will probably not be converted. Rather, the new `makevalid` from https://github.com/go-spatial/geom will be used. For the purposes of this issue, we will convert around the `validate.CleanGeometry`.

**Comment by ARolek** [comment]
@ear7h I think you should skip validate.CleanGeometry as that what's @gdey is working on. I don't think we benefit from that porting effort. Instead, convert from and to the geom types around that step.

**Comment by ear7h** [comment]
@ARolek I was just in the proccess of updating my original comment when you sent this, I included it in the list for information.
